name: sdkwork_mcp_flutter_mobile_core
description: SDKWork MCP Flutter mobile core package
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sdkwork_mcp_app_sdk_generated_flutter:
    path: ../../../../sdks/sdkwork-mcp-app-sdk/sdkwork-mcp-app-sdk-flutter/generated/server-openapi
